require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ArtsTypesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # ArtsType. As you add validations to ArtsType, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    FactoryGirl.attributes_for(:arts_type)
  }

  let(:invalid_attributes) {
    { name: "" }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ArtsTypesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all arts_types as @arts_types" do
      arts_type = ArtsType.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:arts_types)).to eq([arts_type])
    end
  end

  describe "GET #show" do
    it "assigns the requested arts_type as @arts_type" do
      arts_type = ArtsType.create! valid_attributes
      get :show, {:id => arts_type.to_param}, valid_session
      expect(assigns(:arts_type)).to eq(arts_type)
    end
  end

  describe "GET #new" do
    it "assigns a new arts_type as @arts_type" do
      get :new, {}, valid_session
      expect(assigns(:arts_type)).to be_a_new(ArtsType)
    end
  end

  describe "GET #edit" do
    it "assigns the requested arts_type as @arts_type" do
      arts_type = ArtsType.create! valid_attributes
      get :edit, {:id => arts_type.to_param}, valid_session
      expect(assigns(:arts_type)).to eq(arts_type)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new ArtsType" do
        expect {
          post :create, {:arts_type => valid_attributes}, valid_session
        }.to change(ArtsType, :count).by(1)
      end

      it "assigns a newly created arts_type as @arts_type" do
        post :create, {:arts_type => valid_attributes}, valid_session
        expect(assigns(:arts_type)).to be_a(ArtsType)
        expect(assigns(:arts_type)).to be_persisted
      end

      it "redirects to the created arts_type" do
        post :create, {:arts_type => valid_attributes}, valid_session
        expect(response).to redirect_to(ArtsType.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved arts_type as @arts_type" do
        post :create, {:arts_type => invalid_attributes}, valid_session
        expect(assigns(:arts_type)).to be_a_new(ArtsType)
      end

      it "re-renders the 'new' template" do
        post :create, {:arts_type => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do

      new_name = FFaker::Lorem.word
      new_description = FFaker::Lorem.paragraph

      let(:new_attributes) {
        arts_type = { name: new_name , description: new_description }
      }

      it "updates the requested arts_type" do
        arts_type = ArtsType.create! valid_attributes
        put :update, {:id => arts_type.to_param, :arts_type => new_attributes}, valid_session
        arts_type.reload
        expect(arts_type.name).to eq(new_name)
        expect(arts_type.description).to eq(new_description)
      end

      it "assigns the requested arts_type as @arts_type" do
        arts_type = ArtsType.create! valid_attributes
        put :update, {:id => arts_type.to_param, :arts_type => valid_attributes}, valid_session
        expect(assigns(:arts_type)).to eq(arts_type)
      end

      it "redirects to the arts_type" do
        arts_type = ArtsType.create! valid_attributes
        put :update, {:id => arts_type.to_param, :arts_type => valid_attributes}, valid_session
        expect(response).to redirect_to(arts_type)
      end
    end

    context "with invalid params" do
      it "assigns the arts_type as @arts_type" do
        arts_type = ArtsType.create! valid_attributes
        put :update, {:id => arts_type.to_param, :arts_type => invalid_attributes}, valid_session
        expect(assigns(:arts_type)).to eq(arts_type)
      end

      it "re-renders the 'edit' template" do
        arts_type = ArtsType.create! valid_attributes
        put :update, {:id => arts_type.to_param, :arts_type => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested arts_type" do
      arts_type = ArtsType.create! valid_attributes
      expect {
        delete :destroy, {:id => arts_type.to_param}, valid_session
      }.to change(ArtsType, :count).by(-1)
    end

    it "redirects to the arts_types list" do
      arts_type = ArtsType.create! valid_attributes
      delete :destroy, {:id => arts_type.to_param}, valid_session
      expect(response).to redirect_to(arts_types_url)
    end
  end

end
